/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tateticeleste;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Robinson
 */
public final class Tateti extends javax.swing.JFrame {

    /**
     * Creates new form Tateti
     *
     * @param decision
     */
    public Tateti(int decision, int quienEmpieza, boolean vsordenador) {
        opcion = decision;
        this.quienEmpieza = quienEmpieza;
        this.vsordenador = vsordenador;
        initComponents();
        setLocationRelativeTo(null);
        

    }
    private int opcion;
    private int quienEmpieza;
    private boolean vsordenador;
    String[] botones = new String[9];
    Random aleatorio = new Random(System.currentTimeMillis());
    // Producir nuevo int aleatorio entre 0 y 99
    int intAletorio = aleatorio.nextInt(9);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JToggleButton();
        btn2 = new javax.swing.JToggleButton();
        btn7 = new javax.swing.JToggleButton();
        btn6 = new javax.swing.JToggleButton();
        btn9 = new javax.swing.JToggleButton();
        btn8 = new javax.swing.JToggleButton();
        btn4 = new javax.swing.JToggleButton();
        btn3 = new javax.swing.JToggleButton();
        btn5 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();

        btn1.setText("jToggleButton1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("jToggleButton4");

        btn7.setText("jToggleButton6");

        btn6.setText("jToggleButton9");

        btn9.setText("jToggleButton8");

        btn8.setText("jToggleButton2");

        btn4.setText("jToggleButton5");

        btn3.setText("jToggleButton3");

        btn5.setText("jToggleButton7");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TaTeTi Ver. 2");

        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        b1.setFont(new java.awt.Font("DialogInput", 3, 36)); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);

        b2.setFont(new java.awt.Font("DialogInput", 3, 36)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);

        b3.setFont(new java.awt.Font("DialogInput", 3, 36)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);

        b4.setFont(new java.awt.Font("DialogInput", 3, 36)); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4);

        b5.setFont(new java.awt.Font("DialogInput", 3, 36)); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5);

        b6.setFont(new java.awt.Font("DialogInput", 3, 36)); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6);

        b7.setFont(new java.awt.Font("DialogInput", 3, 36)); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7);

        b8.setFont(new java.awt.Font("DialogInput", 3, 36)); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel1.add(b8);

        b9.setFont(new java.awt.Font("DialogInput", 3, 36)); // NOI18N
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel1.add(b9);

        jLabel1.setFont(new java.awt.Font("DialogInput", 3, 36)); // NOI18N
        jLabel1.setText("Tateti");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReiniciar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReiniciar)
                            .addComponent(btnIniciar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String jugadaFor(int a) {
        String escribir = "";
        if (a % 2 == 0 || a == 0) {
            escribir = "X";
        } else {
            escribir = "O";
        }

        opcion++;
        return escribir;
    }

    public void alguienGana(int ganadorString) {
        String escribir;
        if (ganadorString % 2 == 0) {
            escribir = "X";
        } else {
            escribir = "O";
        }
        Seleccion inicio = new Seleccion();
        inicio.setVisible(true);
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, ("Gana la " + escribir));
    }

    public boolean tableroVacio() {
        boolean estadoDelTablero;
        if (b1.getText().equals("") && b2.getText().equals("") && b3.getText().equals("")
                && b4.getText().equals("") && b5.getText().equals("") && b6.getText().equals("")
                && b7.getText().equals("") && b8.getText().equals("") && b9.getText().equals("")) {
            estadoDelTablero = true;
        } else {
            estadoDelTablero = false;
        }
        return estadoDelTablero;
    }

    public void primerJugOrdenador(int aleat) {
        String jugada;
        if (opcion % 2 == 0 || opcion == 0) {
            jugada = "X";
        } else {
            jugada = "O";
        }
        switch (aleat) {
            case 0:
                b1.setText(jugada);
                break;

            case 1:
                b2.setText(jugada);
                break;

            case 2:
                b3.setText(jugada);
                break;

            case 3:
                b4.setText(jugada);
                break;

            case 4:
                b5.setText(jugada);
                break;

            case 5:
                b6.setText(jugada);
                break;

            case 6:
                b7.setText(jugada);
                break;

            case 7:
                b8.setText(jugada);
                break;

            case 8:
                b9.setText(jugada);
                break;

            default:
                juegaOrdenador();
        }

    }

    public void juegaOrdenador() {
        String jugada;

        if (opcion % 2 == 0 || opcion == 0) {
            jugada = "X";
        } else {
            jugada = "O";
        }

        if (vsordenador == true) {
            if (b1.getText().equals(b2.getText()) && b3.getText().equals("")) {
                b3.setText(jugada);
                //alguienGana(opcion - 1);
                opcion++;
                System.out.println("b3 ordenador");

            } else if (b1.getText().equals(b3.getText()) && b2.getText().equals("")) {
                b2.setText(jugada);
                //  alguienGana(opcion - 1);
                opcion++;
                System.out.println("b2 ordenador");

            } else if (b2.getText().equals(b3.getText()) && b1.getText().equals("")) {
                b1.setText(jugada);
                // alguienGana(opcion - 1);
                opcion++;
                System.out.println("b1 ordenador");

                //---------------------------------------------------------
            } else if (b4.getText().equals(b5.getText()) && b6.getText().equals("")) {
                b6.setText(jugada);
                //  alguienGana(opcion - 1);
                opcion++;
                System.out.println("b6 ordenador");

            } else if (b4.getText().equals(b6.getText()) && b5.getText().equals("")) {
                b5.setText(jugada);
                //  alguienGana(opcion - 1);
                opcion++;
                System.out.println("b5 ordenador");

            } else if (b5.getText().equals(b6.getText()) && b4.getText().equals("")) {
                b4.setText(jugada);
                // alguienGana(opcion - 1);
                opcion++;
                System.out.println("b4 ordenador");

                //----------------------------------------------------------
            } else if (b7.getText().equals(b8.getText()) && b9.getText().equals("")) {
                b9.setText(jugada);
                // alguienGana(opcion - 1);
                opcion++;
                System.out.println("b9 ordenador");

            } else if (b8.getText().equals(b9.getText()) && b7.getText().equals("")) {
                b7.setText(jugada);
                //  alguienGana(opcion - 1);
                opcion++;
                System.out.println("b7 ordenador");

            } else if (b7.getText().equals(b9.getText()) && b8.getText().equals("")) {
                b8.setText(jugada);
                //  alguienGana(opcion - 1);
                opcion++;
                System.out.println("b8 ordenador");

                //----------------------------------------------------------
            } else if (b1.getText().equals(b4.getText()) && b7.getText().equals("")) {
                b7.setText(jugada);
                //   alguienGana(opcion - 1);
                opcion++;
                System.out.println("b7 ordenador");

            } else if (b4.getText().equals(b7.getText()) && b1.getText().equals("")) {
                b1.setText(jugada);
                //  alguienGana(opcion - 1);
                opcion++;
                System.out.println("b1 ordenador");

            } else if (b1.getText().equals(b7.getText()) && b4.getText().equals("")) {
                b4.setText(jugada);
                //  alguienGana(opcion - 1);
                opcion++;
                System.out.println("b4 ordenador");

                //----------------------------------------------------------
            } else if (b2.getText().equals(b5.getText()) && b8.getText().equals("")) {
                b8.setText(jugada);
                //  alguienGana(opcion - 1);
                opcion++;
                System.out.println("b8 ordenador");

            } else if (b5.getText().equals(b8.getText()) && b2.getText().equals("")) {
                b2.setText(jugada);
                //   alguienGana(opcion - 1);
                opcion++;
                System.out.println("b2 ordenador");

            } else if (b2.getText().equals(b8.getText()) && b5.getText().equals("")) {
                b5.setText(jugada);
                //   alguienGana(opcion - 1);
                opcion++;
                System.out.println("b5 ordenador");

                //----------------------------------------------------------
            } else if (b3.getText().equals(b6.getText()) && b9.getText().equals("")) {
                b9.setText(jugada);
                //  alguienGana(opcion - 1);
                opcion++;
                System.out.println("b9 ordenador");

            } else if (b6.getText().equals(b9.getText()) && b3.getText().equals("")) {
                b3.setText(jugada);
                //   alguienGana(opcion - 1);
                opcion++;
                System.out.println("b3 ordenador");

            } else if (b3.getText().equals(b9.getText()) && b6.getText().equals("")) {
                b6.setText(jugada);
                //   alguienGana(opcion - 1);
                opcion++;
                System.out.println("b6 ordenador");

                //----------------------------------------------------------
            } else if (b1.getText().equals(b5.getText()) && b9.getText().equals("")) {
                b9.setText(jugada);

                //   alguienGana(opcion - 1);
                opcion++;
                System.out.println("b9 ordenador");

            } else if (b5.getText().equals(b9.getText()) && b1.getText().equals("")) {
                b1.setText(jugada);
                //   alguienGana(opcion - 1);
                opcion++;
                System.out.println("b1 ordenador");

            } else if (b1.getText().equals(b9.getText()) && b5.getText().equals("")) {
                b5.setText(jugada);
                //    alguienGana(opcion - 1);
                opcion++;
                System.out.println("b5 ordenador");

                //----------------------------------------------------------
            } else if (b7.getText().equals(b5.getText()) && b3.getText().equals("")) {
                b3.setText(jugada);
                //    alguienGana(opcion - 1);
                opcion++;
                System.out.println("b3 ordenador");

            } else if (b5.getText().equals(b3.getText()) && b7.getText().equals("")) {
                b7.setText(jugada);
                //  alguienGana(opcion - 1);
                opcion++;
                System.out.println("b7 ordenador");

            } else if (b7.getText().equals(b3.getText()) && b5.getText().equals("")) {
                b5.setText(jugada);
                //   alguienGana(opcion - 1);
                opcion++;
                System.out.println("b5 ordenador");

            } else {
                int aux = opcion;
                //  do {

                switch (intAletorio) {
                    case 0:
                        if (b1.getText().equals("")) {
                            b1.setText(jugada);
                            opcion++;
                        }
                        break;

                    case 1:
                        if (b2.getText().equals("")) {
                            b2.setText(jugada);
                            opcion++;
                        }
                        break;

                    case 2:
                        if (b3.getText().equals("")) {
                            b3.setText(jugada);
                            opcion++;
                        }
                        break;

                    case 3:
                        if (b4.getText().equals("")) {
                            b4.setText(jugada);
                            opcion++;
                        }
                        break;

                    case 4:
                        if (b5.getText().equals("")) {
                            b5.setText(jugada);
                            opcion++;
                        }
                        break;

                    case 5:
                        if (b6.getText().equals("")) {
                            b6.setText(jugada);
                            opcion++;
                        }

                        break;

                    case 6:
                        if (b7.getText().equals("")) {
                            b7.setText(jugada);
                            opcion++;
                        }
                        break;

                    case 7:
                        if (b8.getText().equals("")) {
                            b8.setText(jugada);
                            opcion++;
                        }
                        break;

                    case 8:
                        if (b9.getText().equals("")) {
                            b9.setText(jugada);
                            opcion++;
                        }
                        break;

                    default:
                        break;

                }
                // } while (opcion == aux);

            }
        }
    }

    public void gano() {

        if (b1.getText().equals(b2.getText()) && b1.getText().equals(b3.getText()) && !b1.getText().equals("")) {
            alguienGana(opcion - 1);
        } else if (b1.getText().equals(b4.getText()) && b1.getText().equals(b7.getText()) && !b1.getText().equals("")) {
            alguienGana(opcion - 1);
        } else if (b1.getText().equals(b5.getText()) && b1.getText().equals(b9.getText()) && !b1.getText().equals("")) {
            alguienGana(opcion - 1);
        } else if (b2.getText().equals(b5.getText()) && b2.getText().equals(b8.getText()) && !b2.getText().equals("")) {
            alguienGana(opcion - 1);
        } else if (b3.getText().equals(b5.getText()) && b3.getText().equals(b7.getText()) && !b3.getText().equals("")) {
            alguienGana(opcion - 1);
        } else if (b4.getText().equals(b5.getText()) && b4.getText().equals(b6.getText()) && !b4.getText().equals("")) {
            alguienGana(opcion - 1);
        } else if (b3.getText().equals(b6.getText()) && b3.getText().equals(b9.getText()) && !b3.getText().equals("")) {
            alguienGana(opcion - 1);
        } else if (b7.getText().equals(b8.getText()) && b7.getText().equals(b9.getText()) && !b7.getText().equals("")) {
            alguienGana(opcion - 1);
        }
    }

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed

    }//GEN-LAST:event_btn1ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if (b5.getText().equals("")) {
            b5.setText(jugadaFor(opcion));
        } else {
        }
        juegaOrdenador();
        gano();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        if (b4.getText().equals("")) {
            b4.setText(jugadaFor(opcion));

        } else {
        }
        juegaOrdenador();
        gano();
    }//GEN-LAST:event_b4ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed

        if (b1.getText().equals("")) {
            b1.setText(jugadaFor(opcion));

        } else {
        }
        juegaOrdenador();
        gano();

    }//GEN-LAST:event_b1ActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        Seleccion inicio = new Seleccion();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if (b2.getText().equals("")) {
            b2.setText(jugadaFor(opcion));

        } else {
        }
        juegaOrdenador();
        gano();
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if (b3.getText().equals("")) {
            b3.setText(jugadaFor(opcion));

        } else {
        }
        juegaOrdenador();
        gano();
    }//GEN-LAST:event_b3ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        if (b5.getText().equals("")) {
            b5.setText(jugadaFor(opcion));

        } else {
        }
        juegaOrdenador();
        gano();
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        if (b6.getText().equals("")) {
            b6.setText(jugadaFor(opcion));

        } else {
        }
        juegaOrdenador();
        gano();
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if (b7.getText().equals("")) {
            b7.setText(jugadaFor(opcion));
        } else {
        }
        juegaOrdenador();
        gano();
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if (b8.getText().equals("")) {
            b8.setText(jugadaFor(opcion));
        } else {
        }
        juegaOrdenador();
        gano();
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        if (b9.getText().equals("")) {
            b9.setText(jugadaFor(opcion));
        } else {
        }
        juegaOrdenador();
        gano();
    }//GEN-LAST:event_b9ActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        if (vsordenador == true && tableroVacio() == true && quienEmpieza == 2) {
            primerJugOrdenador(intAletorio);
            opcion++;
        } else {

        }
    }//GEN-LAST:event_btnIniciarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JToggleButton btn1;
    private javax.swing.JToggleButton btn2;
    private javax.swing.JToggleButton btn3;
    private javax.swing.JToggleButton btn4;
    private javax.swing.JToggleButton btn5;
    private javax.swing.JToggleButton btn6;
    private javax.swing.JToggleButton btn7;
    private javax.swing.JToggleButton btn8;
    private javax.swing.JToggleButton btn9;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
